### PR TITLE
Post release v1

### LINKED ISSUE #3: tDynamo startTransaction call doesn't return response after restart
### Summary
After restarting a tDynamo device, when calling the interface function ```startTransaction```, the function does not return a response.  

### Expected Behavior
The ```startTransaction``` function should always return either a response - or throw an error.  The function "hanging" occasionally leads to inconsistent behavior.  

### Steps to Reproduce
- Turn on a tDynamo  
- Hold the button down for 5 seconds (it will beep). Release the button.  
- Once the device has restarted, turn it on again.  
- Connect the device to a web app that uses ```magensa-bluetooth``` (I used the [Playground](https://btplayground.magensa.dev/))
- call the function:  
```javascript
async function test() {
    try {
        const startTrxResp = await device.deviceInterface.startTransaction();
        //The log below will not fire
        console.log(startTrxResp);
    }
    catch(err) {
        console.error(err);
    }
}

```

### Additional Information
This only happens after restarting the device, or if it runs out of batter and is charged again.  Under other circumstances, the function call returns a response.

### PR DESCRIPTION
**Pull request by LukeTurp**
Fixing Issue #3, and updating README.

### CODE REVIEW

**Comment by MagTekTeam** [comment]
Looks good

File: src/devices/scra.js [hunk 1]
```diff
@@ -194,7 +192,7 @@ class Scra extends ScraEmvParser {
                 (commandResp.code !== 918) ? reject(this.buildDeviceErr(commandResp)) :
                     this.setDeviceDateTime()
                     .then( () => this.delayPromise(500) )
-                    .then( () => this.startTransaction(emvOptions) )
+                    .then( () => resolve( this.startTransaction(emvOptions) ) )
```
Comment (LukeTurp) [inline src/devices/scra.js:195]: Wrapping the recursive call in a resolution is what fixes #3

**Review by MagTekTeam — APPROVED** [review]
